### ISSUE TITLE
Add Pacaur support

### ISSUE THREAD

**Issue by thirtythreeforty** [mgattozzi/Alchemist#17]
pacaur is a popular AUR helper like yaourt or aura.  Would it be possible to add support for it? It uses precisely the same syntax as pacman itself.

**Comment by TheDoctorsLife** [comment]
I should be able to add this very soon, I'll send a pr when done. (This wouldn't take much effort to do, so I can do it real fast before finishing support for my distro)

**Comment by mgattozzi** [comment]
This should be fairly easy to accomplish. It's a matter of extending the enum [here](https://github.com/mgattozzi/Alchemist/blob/dev/src/alchemy/arch.rs#L124) to include this then adding it [here](https://github.com/mgattozzi/Alchemist/blob/dev/src/alchemy/arch.rs#L144) to the match statement and then creating an install function at the bottom of the file.

**Comment by mgattozzi** [comment]
@TheDoctorsLife Just make sure to do a rebase off the latest version of dev to avoid merge conflicts if you do submit a PR!
