### ISSUE TITLE
Define Release Roadmap

### ISSUE THREAD

**Issue by mgattozzi** [mgattozzi/alchemist#27]
Currently there is no v0.2.0 release map nor any for the Future. Need to define future goals so it's easier for contributions in the future as well as limiting scope creep for myself

**Comment by mgattozzi** [comment]
V0.2.0 was released. Need to create new road map.

**Comment by TheDoctorsLife** [comment]
You can try [trello](https://trello.com) for future goals.

**Comment by mgattozzi** [comment]
This would be a good fit possibly. I'll look into their github integration

**Comment by TheDoctorsLife** [comment]
There's certainly a slack integration for trello.

**Comment by mgattozzi** [comment]
Which would be fine for internal discussion. It would also allow us to post the board publicly for others to see going forward.

**Comment by TheDoctorsLife** [comment]
This should be pretty much done, will close issue once I'm finished.
