### ISSUE TITLE
Switch to SQLite instead of Postgres

### ISSUE THREAD

**Issue by mgattozzi** [mgattozzi/Alchemist#33]
After discussion with @Hoverbear on irc it made sense to use Postgres instead of SQLite. Why?

- Lightweight compared to Postgres
- No Daemon
- Stored in a file
- Alchemist is doing dead simple queries for relations
- Most distros already have it preinstalled
- No need for security or anything fancy.

Possible complications:
- Diesel might not support the current feature set. This needs to be looked into

**Comment by mgattozzi** [comment]
For reference:
https://www.sqlite.org/whentouse.html

**Comment by Hoverbear** [comment]
\o/
