### ISSUE TITLE
Implement a easier way to add packages and distros to the SQLite db.

### ISSUE THREAD

**Issue by TheDoctorsLife** [mgattozzi/alchemist#36]
Currently it's required to use hard wired ways to add both, I want to see if we can figure out a better/easier way to do this.

**Comment by mgattozzi** [comment]
We could create a helper utility or script for users to generate package or distro additions for migrations.

**Comment by TheDoctorsLife** [comment]
Covered by https://github.com/Alchemist-rs/Forge, once Forge is ready this can be closed.

**Comment by TheDoctorsLife** [comment]
Closing due to #73
